name = "newsletter"
main = "src/index.js"
compatibility_date = "2024-08-16"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "developer-friendly-newsletter"
database_id = "a35f1a13-71e1-4084-8c6c-a54f12ec5fee"
