var quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Imagination is more important than knowledge. - Albert Einstein",
  "Be the change you wish to see in the world. - Mahatma Gandhi",
  "I think, therefore I am. - René Descartes",
  "To be or not to be, that is the question. - William Shakespeare",
  "The unexamined life is not worth living. - Socrates",
  "Know thyself. - Ancient Greek aphorism",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference. - Robert Frost",
  "Be yourself; everyone else is already taken. - Oscar Wilde",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "You must be the change you wish to see in the world. - Mahatma Gandhi",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Genius is one percent inspiration and ninety-nine percent perspiration. - Thomas Edison",
  "The only true wisdom is in knowing you know nothing. - Socrates",
  "Life is what happens to you while you're busy making other plans. - John Lennon",
  "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
  "I have a dream. - Martin Luther King Jr.",
  "The journey of a thousand miles begins with one step. - Lao Tzu",
  "Stay hungry, stay foolish. - Steve Jobs",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Cogito, ergo sum. (I think, therefore I am.) - René Descartes",
  "That which does not kill us makes us stronger. - Friedrich Nietzsche",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "The only impossible journey is the one you never begin. - Tony Robbins",
  "It is not in the stars to hold our destiny but in ourselves. - William Shakespeare",
  "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
  "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that. - Martin Luther King Jr.",
  "The greatest wealth is to live content with little. - Plato",
  "I am the master of my fate: I am the captain of my soul. - William Ernest Henley",
  "No man is an island, entire of itself. - John Donne",
  "To thine own self be true. - William Shakespeare",
  "Give me liberty or give me death. - Patrick Henry",
  "The only way to have a friend is to be one. - Ralph Waldo Emerson",
  "A room without books is like a body without a soul. - Marcus Tullius Cicero",
  "The mind is everything. What you think you become. - Buddha",
  "Not all those who wander are lost. - J.R.R. Tolkien",
  "The best revenge is massive success. - Frank Sinatra",
  "I came, I saw, I conquered. - Julius Caesar",
  "It is better to be hated for what you are than to be loved for what you are not. - André Gide",
  "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
  "Ask not what your country can do for you – ask what you can do for your country. - John F. Kennedy",
  "If you tell the truth, you don't have to remember anything. - Mark Twain",
  "Doubt is the beginning of wisdom. - Aristotle",
  "To err is human; to forgive, divine. - Alexander Pope",
  "All that glitters is not gold. - William Shakespeare",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "Necessity is the mother of invention. - Plato",
  "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
  "I think therefore I am. - René Descartes",
  "Knowledge is power. - Sir Francis Bacon",
  "The pen is mightier than the sword. - Edward Bulwer-Lytton",
  "Fortune favors the bold. - Virgil",
  "A journey of a thousand miles begins with a single step. - Lao Tzu",
  "Be the change you wish to see in the world. - Mahatma Gandhi",
  "In the middle of difficulty lies opportunity. - Albert Einstein",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only true wisdom is in knowing you know nothing. - Socrates",
  "It is during our darkest moments that we must focus to see the light. - Aristotle",
  "Do not go gentle into that good night. - Dylan Thomas",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "If you can't explain it simply, you don't understand it well enough. - Albert Einstein",
  "Life is what happens to you while you're busy making other plans. - John Lennon",
  "The secret of getting ahead is getting started. - Mark Twain",
  "Be yourself; everyone else is already taken. - Oscar Wilde",
  "You only live once, but if you do it right, once is enough. - Mae West",
  "Whether you think you can or you think you can't, you're right. - Henry Ford",
  "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. - Mark Twain",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
  "Those who dare to fail miserably can achieve greatly. - John F. Kennedy",
  "A person who never made a mistake never tried anything new. - Albert Einstein",
  "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
  "The question isn't who is going to let me; it's who is going to stop me. - Ayn Rand",
  "Imagination is the beginning of creation. - George Bernard Shaw",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change. - Charles Darwin",
  "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
  "The only way to have a friend is to be one. - Ralph Waldo Emerson",
  "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
  "If you want to go fast, go alone. If you want to go far, go together. - African Proverb",
  "The mind is everything. What you think you become. - Buddha",
  "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
  "The best way to predict the future is to create it. - Peter Drucker",
  "If you don't stand for something you will fall for anything. - Gordon A. Eadie",
  "It always seems impossible until it's done. - Nelson Mandela",
  "What we think, we become. - Buddha",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Do what you can, with what you have, where you are. - Theodore Roosevelt",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Everything has beauty, but not everyone sees it. - Confucius",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world. - Anne Frank",
  "",
];

export default function getQuote() {
  return quotes[Math.floor(Math.random() * quotes.length)];
}
